### ISSUE TITLE
The application is very heavy 

### ISSUE THREAD

**Issue by Aseel67** [deku-messaging/Deku-SMS-Android#129]
![Screenshot_٢٠٢٣١١٠٤_١٨٢٩٣٧_Deku SMS](https://github.com/deku-messaging/Deku-SMS-Android/assets/141158270/19e87887-d90f-42ac-98f1-29e39d472b1e)
It seems that the application cannot accommodate many conversations because the application freezes frequently 
Also when you start a chat please the transmission failed message appears

**Comment by sherlockwisdom** [comment]
@Aseel67 

Please can you screenshot the transmission failed - would help to track it down and fix the issue.

Speed issues being worked, should load faster by next update 👍🏽

**Comment by sherlockwisdom** [comment]
It should be faster now with the latest v 0.26.0. Please feel free to re-open this if the issue persist
