### ISSUE TITLE
make request encryption header less obnoxious

### ISSUE THREAD

**Issue by theotheroracle** [deku-messaging/Deku-SMS-Android#131]
it covers like a lot of the history, and you can't dismiss it permenantly for any conversation, and disabling the request header seems to leave no way to start an encrypted conversation

**Comment by Dyras** [comment]
Indeed. Silence handled this nicer I think. Unless I'm mistaken, it had "enable encryption" as a lock button you could click in the top right corner of a chat.

**Comment by sherlockwisdom** [comment]
Please let me know what you think in the newest version 0.26.0.

There are currently not many apps that provide the request for users, so I haven't been able to find one I can mirror off. 

Please let me know any suggestions

**Comment by theotheroracle** [comment]
i think it would be nice if there was an unlocked / locked icon next to the call button, it could be red when unencrypted to draw attention, and have a confirmation popup like "do you want to send and encryption request" as it is now, i accidentally sent a request when trying to dismiss the button

**Comment by sherlockwisdom** [comment]
Sounds great! I added a button on 0.29.0.
It has a theming issue but if you look closely near the call button (in dark theme) you'd see one 😂

**Comment by theotheroracle** [comment]
oh yeah i totally missed that lol
