### ISSUE TITLE
Conversations, Priority Conversations and Message Bubbles 

### ISSUE THREAD

**Issue by Wave6677** [deku-messaging/Deku-SMS-Android#138]
Introduced in Android 11 this feature has always been the deciding factor in choosing a primary client for me, and many others I'm sure. Being able to not have to open the app, while being able to read the chat and respond to messages would be a great feature, especially since the framework is built into android.

**Comment by sherlockwisdom** [comment]
I have just pushed a fix for this, should be available in the tomorrow's update

**Comment by Wave6677** [comment]
> I have just pushed a fix for this, should be available in the tomorrow's update

Just downloaded the update that released about 6 hours ago as of writing and I'm not seeing notifications/conversations/bubbles. Is there a hidden setting or is the update delayed? Thanks for the hard work by the way, this app seems nicely designed so far UI wise :)
