### ISSUE TITLE
Many links aren't clickable

### ISSUE THREAD

**Issue by Dyras** [deku-messaging/Deku-SMS-Android#147]
Hello. For whatever reason, some links aren't clickable. Or rather, only parts of them are clickable. A regex issue perhaps?

See the image
![Screenshot_20231129-213342_1](https://github.com/deku-messaging/Deku-SMS-Android/assets/12563436/441ce180-bc0d-4101-a468-bc9427812ebd)

**Comment by sherlockwisdom** [comment]
That's correct, this was a regex issue. I've made some updates 0.32.0 - I think should fix this. I don't think it captures all the cases yet but should fix this one :+1:

**Comment by Dyras** [comment]
@sherlockwisdom 
Question marks in the links still break them.
