### ISSUE TITLE
EEE compatibility with Silence

### ISSUE THREAD

**Issue by iiitomo** [deku-messaging/Deku-SMS-Android#155]
Wish Deku could do End-to-End encrypted SMS with Silence users.

**Comment by Massedil** [comment]
I tried with the latest version 0.37 today to create a conversation with Silence but without success. Is it normal that this issue is closed as completed?

**Comment by sherlockwisdom** [comment]
Hopefully someone who understands the inner workings of Silence and would want to collaborate would work on this. I am open to assisting however best I can. 

Keeping this issue as a call for help

**Comment by sherlockwisdom** [comment]
Please anyone should feel free to re-open this once they can begin working on getting the internals of Silence to work with the internals of Deku SMS
