### ISSUE TITLE
fails to start secure conversation

### ISSUE THREAD

**Issue by iiitomo** [deku-messaging/Deku-SMS-Android#156]
Requests systematically fail when trying to start encrypted conversation between 2 phones that have Deku 0.32.0 .
Let me know if you need additional info.

**Comment by sherlockwisdom** [comment]
Please when you systematically fail, does it fail to send (with a red sticker at the bottom saying failed) or is it the recipient does not receive the message?

Please can you include screenshots or [logs](https://developer.android.com/studio/debug/bug-report#bugreportdevice) if you have them?

**Comment by sherlockwisdom** [comment]
It is possible you service provider does not support sending SMS messages through the Data channels. Without the messages being sent (showing it failed to sent), the user cannot receive the SMS message and cannot secure the conversation.

Does regular SMS message work for you?
