### ISSUE TITLE
App always asks to secure contacts that can't be responded to 

### ISSUE THREAD

**Issue by Dyras** [deku-messaging/Deku-SMS-Android#160]
Hello. Just updated the app to 0.33.0 and now every one-sided chat with my bank, my phone carrier, etc has a request to "secure the chat" at the top. So every chat that is a name rather than a number, basically. 

Anything that can be done about that? Maybe it's just a case of accidentally writing true instead of false in some place?

**Comment by sherlockwisdom** [comment]
Now fixed in 0.34.0
