### ISSUE TITLE
hide Encrypted tab by default

### ISSUE THREAD

**Issue by iiitomo** [deku-messaging/Deku-SMS-Android#164]
Please hide Encrypted tab by default.

**Comment by Dyras** [comment]
Agree! If the app's purpose is to be as normie-friendly as possible, this is just extra confusion IMO.

**Comment by sherlockwisdom** [comment]
Pushed a commit for this, would be removed by default in 0.36.0

**Comment by Cwpute** [comment]
I'd suggest entirely removing the "Encrypted" tab in the future, and only differentiate encrypted from unencrypted conversations with a small lock icon or some other icon below contact images, or at the end of every encrypted message (as Silence did if i remember well).
You could also change the shape of the contact'is image badge to a pentagon maybe ? or add an outer-ring to their imge badge to visually iventify them as "protected".

**Comment by Aryan-Chauhan** [comment]
I came here to request the same.

So, I upvoted this.
