### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Cwpute** [deku-messaging/Deku-SMS-Android#166]
Would you consider localizing this app ?

I know it might be a bit early in its conception, but having localized text could help reach a bigger audience.
I've personally used crowdsourced localization platforms (Crowdin and Weblate) and i think they work really well. I would be willing to help with the french translation myself!

**Comment by Cwpute** [comment]
So did you put Deku on a localization platform ?
If so, could you provide a link here for us to start translating?

**Comment by sherlockwisdom** [comment]
I have no experience with localization platforms, but I will take a look at
your suggestions - I will share the link once I do

French is currently done, any other languages will be greatly appreciated

**Comment by sherlockwisdom** [comment]
I will close this for now, I am hoping some volunteers will step up to help with localizing for their needs. Will re-open this whenever a request for a new language is made and someone willing to work on it
