### ISSUE TITLE
Three feature requests:

### ISSUE THREAD

**Issue by Aryan-Chauhan** [deku-messaging/Deku-SMS-Android#173]
1. Pure black dark mode.

2. Ability to hide the "Encrypted" tab.

3. When you open any conversation, three icons appear on the top right corner: Encrypt, Call & Three Dots.
Please add the option to hide "Encrypt" icon.

Thank you!

**Comment by Dyras** [comment]
2 is done but I don't think it's been pushed out through F-Droid yet:

https://github.com/deku-messaging/Deku-SMS-Android/issues/164
