### ISSUE TITLE
Deku SMS not sending SMS messages

### ISSUE THREAD

**Issue by CoolCrescent186** [deku-messaging/Deku-SMS-Android#182]
It doesn't matter whether I have the secure chat thingy installed. I can neither make nor receive messages using Deku SMS. My carrier is Google Fi. I can send messages using QKSMS. When I click "send", the message doesn't even appear to have been sent, it just vanishes.

**Comment by sherlockwisdom** [comment]
Please it is possible to follow this steps to capture the bug and reason why it's crashing and share with me to:
 dekusms@smswithoutborders.com

https://developer.android.com/studio/debug/bug-report#bugreportdevice

**Comment by CoolCrescent186** [comment]
Excuse me for not replying: shortly after creating this bug I learned that the behavior is tied to a faulty modem manager in my phone (nio), and I got caught up trying to make it work. I tested with another device (kiev), and it works fine except for notifications, which I'm not even sure if that's a feature.

**Comment by sherlockwisdom** [comment]
Hello, good to hear it's sorted - the issue with the notifications happens, it's a persistent bug I will work on that soon. Once you leave the app and return you should be able to start receiving notifications again. In case it continues to not work for you, there is an open issue for it, we can continue debugging it from there
