### ISSUE TITLE
No notifications on incoming messages

### ISSUE THREAD

**Issue by TX9G9qBxid** [deku-messaging/Deku-SMS-Android#189]
No notifications of any kind on device when SMS is incoming. 
All necessary permissions are granted. 

Details and testing: 
Device: Google Pixel 7a
OS: GrapheneOS (latest)
Appversion: tested with both 0.35.0 and 0.36.0
Repository: F-Droid

**Comment by sherlockwisdom** [comment]
This usually fixes itself after you close an re-open the app for the very first time; has to do with the Android notification channels.

Please feel free to re-open this if the issue persist after multiple entries to the app
