### ISSUE TITLE
Conversations are not kept archived

### ISSUE THREAD

**Issue by Albirew** [deku-messaging/Deku-SMS-Android#196]
Descritopn:
On f-droid latest (0.36.0), conversations are not kept archived:

Steps:
1. archive one or more conversations
2. change page (go to settings, archives, quit app, whatever
3. return to main window

Expected behavior:
archived conversations not showing except when going into archives.

Actual behavior: 
All conversations are showing, and archives is empty.

Informations:
- Version: 0.36.0 f-droid
- Hardware: Oneplus One (ARMv7) and Google Pixel7 (ARMv8)

**Comment by sherlockwisdom** [comment]
Fixed in 0.37.0 - update coming to fdroid soon
