### ISSUE TITLE
crashing when opening

### ISSUE THREAD

**Issue by comiconomenclaturist** [deku-messaging/Deku-SMS-Android#201]
Installed the app from f droid recently. Just updated it and it keeps crashing when opening. Currently unusable on my moto g50, android12

**Comment by sherlockwisdom** [comment]
Sorry about that, they is a database migration issue with the latest build. Please clear your cache and storage for the app and it should work just fine

**Comment by comiconomenclaturist** [comment]
Thanks, that fixed it
