### ISSUE TITLE
How to receive the request on a web-server (PHP), where are the specs/API?

### ISSUE THREAD

**Issue by shula** [deku-messaging/Deku-SMS-Android#206]
1. I'd like to to run the gateway server on my existing, tiny web-server; But I can't find how.
I will write the script by myself, but I can't figure out the HTTP request.

 2. What my server should be looking for, in the request it receives from the Deku phone app?

3. Are there specs / API description?

# What I've done so far:
I've set up a simple PHP server (on Apache)
I created a gateway in the Deku app.
The server is logging the request variables; I can see the metadata,
---> but I can't find the message body

P.S.:
I will receive 2-3 sms a day, so I don't require queues (or even a database; for my needs a flat file or sqlite will suffice)
Also, since the server is private, and is using SSL, I don't require additional encryption.

Thanks!

**Comment by sherlockwisdom** [comment]
The messages are forwarded as json. Be sure you're checking for incoming
json and not forms or other formats.

Here's a link to the API specifications and json key-values you should
expect

https://github.com/deku-messaging/Deku-SMS-Android?tab=readme-ov-file#-forward-incoming-messages-to-cloud

**Comment by shula** [comment]
For future visitors to this thread: example how to read the request in PHP.
(consider adding this snippet to the docs)
```
<?php
	$json = file_get_contents('php://input');
	$d = json_decode($json, true);
	$sender = $d['address'];
	#...
?>
```
