### ISSUE TITLE
app stay in reconnecting state forever with amqp connection

### ISSUE THREAD

**Issue by unixfox** [deku-messaging/Deku-SMS-Android#221]
Hello,

I tried to connect dekusms to a rabbitmq server with this config:
![image](https://github.com/deku-messaging/Deku-SMS-Android/assets/4016501/4dba2717-1945-4be0-a70b-9e7a6a1a5e18)
![image](https://github.com/deku-messaging/Deku-SMS-Android/assets/4016501/39233ba1-f060-48b1-8369-140d24df48d1)

But it keeps saying that deku sms is reconnecting:
![image](https://github.com/deku-messaging/Deku-SMS-Android/assets/4016501/f12b7a88-faaf-41b3-b9cc-9406f57fe845)

I know that it's connected because it appears in the connected clients of the admin UI of rabbitmq:
![image](https://github.com/deku-messaging/Deku-SMS-Android/assets/4016501/62c10658-f475-49cc-a282-da421ef74e51)

Did I encountered a bug or did I missconfigure something?

Thank you in advance for the help.

**Comment by sherlockwisdom** [comment]
It's a bug, should fix this in the next release
