### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by MXC48** [deku-messaging/Deku-SMS-Android#223]
The input field grows abnormally after you send a message or delete the text
Android 13 LineageOS 21
Latest version![Screenshot_20240316-225713_Deku SMS.png](https://github.com/deku-messaging/Deku-SMS-Android/assets/123580315/8e251691-cbd9-471f-9b3b-a44e3f92796f)

**Comment by sherlockwisdom** [comment]
fixed in v44
