### ISSUE TITLE
Program crashes when dialing multiple secure conversations

### ISSUE THREAD

**Issue by Lattiin** [deku-messaging/Deku-SMS-Android#224]
Thank you very much for this app!
When I try to dial multiple secure conversations in succession to another person, the program will first roll back abnormally, and then the program will crash when I try to dial secure conversations again; this problem may only occur if the dial is repeated multiple times in a short period of time.
The device I use is a virtual device of Android Studio, the Android version is API26, and the program version is 0.36.0.

**Comment by sherlockwisdom** [comment]
Hello, I believe those are some real bugs faced with the older versions - please try with the latest releases which support feedback forward secrecy for communications and has fixed most of the bugs in the older versions. I will strongly encourage v0.43.0 and a fresh install to avoid any database conflicts.

**Comment by Lattiin** [comment]
Thank you very much for your reply, I will look for the latest version from F-Droid and install them.
