### ISSUE TITLE
The program cannot view historical dialogue

### ISSUE THREAD

**Issue by WispaTara** [deku-messaging/Deku-SMS-Android#225]
Hello！

When I tried to view the information I had sent from the main interface of the program, the program exited.
I think I should be able to view the information I have sent.

 - Device: Pixel 7a
 - OS: Android 7
 - Version of the App: 0.36.0

Cheers,

**Comment by sherlockwisdom** [comment]
Hello, sorry about that. Please try with the latest releases such as 0.43.0. Must of this bugs have been fixed in them
