### ISSUE TITLE
Unblock Message

### ISSUE THREAD

**Issue by akashappscale** [deku-messaging/Deku-SMS-Android#243]
List<String> threadIds = new ArrayList<>();
                        for (ThreadedConversationsTemplateViewHolder viewHolder :
                                threadedConversationRecyclerAdapter.selectedItems.getValue().values()) {
                            threadIds.add(viewHolder.id);
                        }
                        ThreadingPoolExecutor.executorService.execute(new Runnable() {
                            @Override
                            public void run() {
                                threadedConversationsViewModel.unblock(getContext(), threadIds);
                            }
                        });
                        threadedConversationRecyclerAdapter.resetAllSelectedItems();
                        return true;
                        
                        
                        
                        
                        signal mesaage Unblock karvo che aama multipal message unblock thay che

**Comment by akashappscale** [comment]
> List threadIds = new ArrayList<>(); for (ThreadedConversationsTemplateViewHolder viewHolder : threadedConversationRecyclerAdapter.selectedItems.getValue().values()) { threadIds.add(viewHolder.id); } ThreadingPoolExecutor.executorService.execute(new Runnable() { @OverRide public void run() { threadedConversationsViewModel.unblock(getContext(), threadIds); } }); threadedConversationRecyclerAdapter.resetAllSelectedItems(); return true;
> 
> ```
>                     signal mesaage Unblock karvo che aama multipal message unblock thay che
> ```

?

**Comment by sherlockwisdom** [comment]
I do not understand this issue, closing. Please re-open anytime with more details
