### ISSUE TITLE
No message delivery receipts

### ISSUE THREAD

**Issue by moforemmanuel** [deku-messaging/Deku-SMS-Android#74]
It is important to some users to know if messages they send reach the receiver, that way, they don't have to resend the message.

**Comment by sherlockwisdom** [comment]
Hi @moforemmanuel , currently there is the delivered notification below on the message when the messages have been delivered. 

For older messages, clicking on them would show their status, please let me know if this isn't the case for you

![Screenshot_20230602-175500.png](https://github.com/deku-messaging/Deku-SMS-Android/assets/10544512/7fcf1182-89f9-45f9-99bc-8cfefec5180e)

**Comment by moforemmanuel** [comment]
Oh I see @sherlockwisdom. Thanks for the feedback. Didn't notice this.
